# Generated by Django 4.1.5 on 2023-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='query',
            field=models.JSONField(default={}),
        ),
    ]
